name: 'learn-fastapi'

services:
  db:
    image: postgres:16.4-alpine
    container_name: learn-db
    restart: unless-stopped
    ports:
      - 54322:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db_data: